# Generated by Django 2.0.4 on 2018-08-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone'),
        ),
    ]
